### PR TITLE
Test snapshot updates

### PR DESCRIPTION
**Pull request by krassowski**
Test PR to check if bot updates snapshots

### CODE REVIEW

**Comment by krassowski** [comment]
bot please update playwright snapshots

**Comment by krassowski** [comment]
Yup, it's working: https://github.com/krassowski/nbdime/actions/runs/6059709025

**Comment by krassowski** [comment]
@HaudinFlorence I invited you to this fork so you can see the actions in the link above as they progress.

**Comment by HaudinFlorence** [comment]
@krassowski I am probably missing something. The windows ui-test are still red, aren't they ?

**Comment by krassowski** [comment]
Yes because the update action errored on `npm` command, see link above. It should be `npm install` followed by `npm run build` I think

**Comment by krassowski** [comment]
bot please update playwright snapshots

**Comment by krassowski** [comment]
bot please update playwright snapshots (again and again)

**Comment by krassowski** [comment]
bot please update playwright snapshots (again and again) one more time

**Comment by krassowski** [comment]
So it works for one version at a time, and the remaining ones error out. This is expected because snapshots are per OS, not per Python version. Let's only update snapshots on latest version and run the Linux/windows script sequentially

```
error: The following untracked working tree files would be overwritten by merge:
	ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/Test1-test-for-the-merge-application-for-note-3788b-d-1-conflict-choose-left-version-for-conflict-1-win32.png
Updating ec2fd4b..ab716cb
	ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/Test1-test-for-the-merge-application-for-note-9c155--conflict-choose-central-version-for-conflict-1-win32.png
	ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/Test1-test-for-the-merge-application-for-note-a6996--conflict-open-an-example-and-take-a-snapshot-1-win32.png
	ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/Test1-test-for-the-merge-application-for-note-cd19b--1-conflict-choose-right-version-for-conflict-1-win32.png
	ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/Test2-test-for-the-merge-application-for-note-119a9--conflict-open-an-example-and-take-a-snapshot-1-win32.png
	ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/Test2-test-for-the-merge-application-for-note-424ad-me-length-with-0-conflict-choose-left-version-1-win32.png
	ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/Test2-test-for-the-merge-application-for-note-6b777-length-with-0-conflict-choose-central-version-1-win32.png
	ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/Test2-test-for-the-merge-application-for-note-eecfd-e-length-with-0-conflict-choose-right-version-1-win32.png
Please move or remove them before you merge.
Aborting
[test-pr 5bbf1b3] Update Playwright Snapshots
 8 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/Test1-test-for-the-merge-application-for-note-3788b-d-1-conflict-choose-left-version-for-conflict-1-win32.png
 create mode 100644 ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/Test1-test-for-the-merge-application-for-note-9c155--conflict-choose-central-version-for-conflict-1-win32.png
 create mode 100644 ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/Test1-test-for-the-merge-application-for-note-a6996--conflict-open-an-example-and-take-a-snapshot-1-win32.png
 create mode 100644 ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/Test1-test-for-the-merge-application-for-note-cd19b--1-conflict-choose-right-version-for-conflict-1-win32.png
 create mode 100644 ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/Test2-test-for-the-merge-application-for-note-119a9--conflict-open-an-example-and-take-a-snapshot-1-win32.png
 create mode 100644 ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/Test2-test-for-the-merge-application-for-note-424ad-me-length-with-0-conflict-choose-left-version-1-win32.png
 create mode 100644 ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/Test2-test-for-the-merge-application-for-note-6b777-length-with-0-conflict-choose-central-version-1-win32.png
 create mode 100644 ui-tests/tests/nbdime-merge-test2.spec.ts-snapshots/Test2-test-for-the-merge-application-for-note-eecfd-e-length-with-0-conflict-choose-right-version-1-win32.png
Run git config push.default upstream
To https://github.com/krassowski/nbdime
 ! [rejected]        test-pr -> test-pr (non-fast-forward)
error: failed to push some refs to 'https://github.com/krassowski/nbdime'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by krassowski** [comment]
bot please update playwright snapshots

**Comment by HaudinFlorence** [comment]
> Yes because the update action errored on `npm` command, see link above. It should be `npm install` followed by `npm run build` I think

It seems logical. Sorry I indeed forgot `npm install`

**Comment by HaudinFlorence** [comment]
> So it works for one version at a time, and the remaining ones error out. This is expected because snapshots are per OS, not per Python version. Let's only update snapshots on latest version and run the Linux/windows script sequentially

I don't see how to change `test.yml` accordingly. Because there is no command in the script to update the snapshots explicitly.

**Comment by krassowski** [comment]
Just merge https://github.com/HaudinFlorence/nbdime/pull/9 :)

**Comment by HaudinFlorence** [comment]
Ok 👍🏻

**Comment by krassowski** [comment]
The `test.yml` itself is fine it can test the same snapshot across multiple Python versions. We only need to avoid re-running it multiple times when updating snapshots, which is already done in https://github.com/HaudinFlorence/nbdime/pull/9.

**Pull request closed without merging**
